inherit_from:
  - .rubocop-airbnb.yml

AllCops:
  TargetRubyVersion: 2.7 
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 130

Airbnb/OptArgParameters:
  Enabled: false
